routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'MainController@index')->name('site.index');

Route::get('/about', 'AboutController@index')->name('site.about');

Route::get('/contact', 'ContactController@index')->name('site.contact');

Route::post('/contact/send', 'ContactController@sendMessage')->name('site.contact.send');

Route::get('/login', 'LoginController@index')->name('site.login');

Route::post('/login', 'LoginController@authentication')->name('site.auth');

Route::middleware('auth.basic')->prefix('/app')->group(function() {

    Route::get('/home', 'HomeController@index')->name('app.home');

    Route::get('/logout', 'LoginController@logout')->name('app.logout');

    // Route::get('/clients', 'ClientController@index')->name('app.clients');

    Route::get('/suppliers', 'SupplierController@index')->name('app.suppliers');
    Route::get('/suppliers/add', 'SupplierController@add')->name('app.suppliers.add');
    Route::post('/suppliers/save', 'SupplierController@save')->name('app.suppliers.save');
    Route::get('/suppliers/edit/{id}', 'SupplierController@edit')->name('app.suppliers.edit');
    Route::get('/suppliers/delete/{id}', 'SupplierController@delete')->name('app.suppliers.delete');

    Route::resource('products', 'ProductController');

    Route::resource('clients', 'ClientController');

    Route::resource('solicitations', 'SolicitationController');

    Route::resource('clients-solicitations', 'ClientSolicitationController');

});

app/Solicitation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Solicitation extends Model
{

    //
    protected $table = 'solicitations';

    protected $fillable = ['client_id'];

    public function clients()
    {
        return $this->belongsTo('App\Client', 'client_id', 'id');
    }

    public function products()
    {
        return $this->belongsToMany('App\Product', 'client_solicitations')->withPivot(['id']);
    }

}

app/Http/Controllers/SolicitationController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Solicitation;
use Illuminate\Http\Request;

class SolicitationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if (!empty($request->all())) {

            $solicitationsList = Solicitation::with(['clients'])
                ->where('client_id', 'like', "%" . $request->input('name')."%")
                ->paginate(20);

        } else {
            $solicitationsList = Solicitation::with(['clients'])->paginate(20);
        }

        return view('app.solicitation.index', ['solicitationsList' => $solicitationsList, 'queryParams' => $request->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $clientList = Client::all();

        return view('app.solicitation.create', ['clientList' => $clientList]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate(
            [
                'client_id' => 'exists:clients,id',
            ],
            [
                'required' => 'O campo deve ser preenchido!',
                'min' => 'O campo deve conter no mínimo 3 caracteres!',
                'max' => 'Limite de caracteres atingido!'
            ]
        );

        $solicitation = new Solicitation();
        $solicitation->fill($request->all());

        if ($solicitation->save()) {
            return redirect()->route('solicitations.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $solicitation = Solicitation::find($id);

        $clientList = Client::all();

        return view('app.solicitation.show', ['solicitation' => $solicitation, 'clientList' => $clientList]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $solicitation = Solicitation::find($id);

        $clientList = Client::all();

        return view('app.solicitation.edit', ['solicitation' => $solicitation, 'clientList' => $clientList]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate(
            [
                'client_id' => 'exists:clients,id',
            ],
            [
                'required' => 'O campo deve ser preenchido!',
                'min' => 'O campo deve conter no mínimo 3 caracteres!',
                'max' => 'Limite de caracteres atingido!'
            ]
        );

        $solicitation = Solicitation::find($id);

        if ($solicitation->update($request->all())) {
            return redirect()->route('solicitations.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/app/solicitation/create.blade.php
@extends('app.layouts.default')

@section('title', 'Pedidos')

@section('content-body')
    <div class="page-title-small">
        <h1>Pedidos - Adicionar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('solicitations.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('solicitations.store') }}" method="post">
                @csrf

                <select name="client_id">
                    <option value=""> -- Selecione um Cliente -- </option>
                    @foreach ($clientList as $client)
                        <option value="{{$client->id}}" {{ (old('client_id') == $client->id) ? 'selected' : '' }} >{{ $client->name }}</option>
                    @endforeach
                </select>
                @component('site.layouts.errors', ["inputName" => "client_id"]) @endcomponent

                <button type="submit">Salvar</button>

            </form>

        </div>

    </div>
@endsection

resources/views/app/solicitation/edit.blade.php
@extends('app.layouts.default')

@section('title', 'Pedidos')

@section('content-body')
    <div class="page-title-small">
        <h1>Pedidos - Editar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('solicitations.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('solicitations.update', [$solicitation->id]) }}" method="post">
                @csrf
                @method('PUT')

                <select name="client_id">
                    @foreach ($clientList as $client)
                        <option value="{{$client->id}}" {{ (old('client_id') == $client->id || $solicitation->client_id == $client->id) ? 'selected' : '' }} >{{ $client->name }}</option>
                    @endforeach
                </select>
                @component('site.layouts.errors', ["inputName" => "client_id"]) @endcomponent

                <button type="submit">Salvar</button>

            </form>

        </div>

    </div>
@endsection

resources/views/app/solicitation/index.blade.php
@extends('app.layouts.default')

@section('title', 'Pedidos')

@section('content-body')
    <div class="page-title-small">
        <h1>Pedidos</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('solicitations.create') }}">Novo</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('solicitations.index') }}" method="get">
                @csrf
                <input type="text" name="name" placeholder="Nome">
                <input type="text" name="email" placeholder="E-mail">
                <input type="text" name="cpfCnpj" placeholder="CPF/CNPJ">
                <input type="text" name="zipCode" placeholder="CEP">

                <button type="submit">Pesquisar</button>

            </form>

        </div>

    </div>

    <div class="informacao-pagina">

        <div style="width: 90%; margin-left: auto; margin-right: auto; ">

            <table border="1" width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Cliente</th>
                        <th>Produtos</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($solicitationsList as $solicitation)

                        <tr>
                            <td>
                                {{ $solicitation->id }}
                            </td>
                            <td>
                                {{ $solicitation->clients->name }}
                            </td>
                            <td>
                                <a href="{{ route('clients-solicitations.create', ['solicitation' => $solicitation->id]) }}">Adicionar Produto</a>
                            </td>
                            <td>
                                <a href="{{ route('solicitations.show', $solicitation->id) }}">Visualizar</a>
                                <a href="{{ route('solicitations.edit', $solicitation->id) }}">Editar</a>

                                <form action="{{ route('solicitations.destroy', $solicitation->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit">Excluir</button>
                                </form>

                            </td>
                        </tr>

                    @endforeach
                </tbody>

                <footer>
                    <tr>
                        <td colspan="2"></td>
                        <td>
                            Total - {{ $solicitationsList->total() }}
                        </td>
                    </tr>
                </footer>
            </table>

            <div>

                {{ $solicitationsList->appends($queryParams)->links() }}

            </div>

        </div>

    </div>
@endsection

resources/views/app/solicitation/show.blade.php
@extends('app.layouts.default')

@section('title', 'Pedidos')

@section('content-body')
    <div class="page-title-small">
        <h1>Pedidos - Editar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('solicitations.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

                <input disabled type="text" name="id" value="{{ $solicitation->id ?? old('id') }}">

                <select name="client_id" disabled>
                    @foreach ($clientList as $client)
                        <option value="{{$client->id}}" {{ ($solicitation->client_id == $client->id) ? 'selected' : '' }} >{{ $client->name }}</option>
                    @endforeach
                </select>

        </div>

    </div>
@endsection