routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'MainController@index')->name('site.index');

Route::get('/about', 'AboutController@index')->name('site.about');

Route::get('/contact', 'ContactController@index')->name('site.contact');

Route::post('/contact/send', 'ContactController@sendMessage')->name('site.contact.send');

Route::get('/login', 'LoginController@index')->name('site.login');

Route::post('/login', 'LoginController@authentication')->name('site.auth');

Route::middleware('auth.basic')->prefix('/app')->group(function() {

    Route::get('/home', 'HomeController@index')->name('app.home');

    Route::get('/logout', 'LoginController@logout')->name('app.logout');

    // Route::get('/clients', 'ClientController@index')->name('app.clients');

    Route::get('/suppliers', 'SupplierController@index')->name('app.suppliers');
    Route::get('/suppliers/add', 'SupplierController@add')->name('app.suppliers.add');
    Route::post('/suppliers/save', 'SupplierController@save')->name('app.suppliers.save');
    Route::get('/suppliers/edit/{id}', 'SupplierController@edit')->name('app.suppliers.edit');
    Route::get('/suppliers/delete/{id}', 'SupplierController@delete')->name('app.suppliers.delete');

    Route::resource('products', 'ProductController');

    Route::resource('clients', 'ClientController');

    Route::resource('solicitations', 'SolicitationController');

    Route::resource('clients-solicitations', 'ClientSolicitationController');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';

    protected $fillable = ['name', 'description', 'weight', 'measurement_id', 'supplier_id'];

    public function measurement()
    {
        return $this->belongsTo('App\Measurement');
    }

    public function supplier()
    {
        return $this->belongsTo('App\Supplier');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Measurement;
use App\Product;
use App\Supplier;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (!empty($request->all())) {

            $productsList = Product::with(['measurement', 'supplier'])->where('name', 'like', "%" . $request->input('name')."%")
                    ->where('description', 'like', "%" . $request->input('description') . "%")
                    ->where('weight', 'like', "%" . $request->input('weight') . "%")
                    ->where('measurement_id', 'like', "%" . $request->input('measurement_id') . "%")
                    ->paginate(20);

        } else {
            $productsList = Product::with(['measurement', 'supplier'])->paginate(20);
        }

        return view('app.product.index', ['productsList' => $productsList, 'queryParams' => $request->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $measurementList = Measurement::all();

        $suppliersList = Supplier::all();

        return view('app.product.create', ['measurementList' => $measurementList, 'suppliersList' => $suppliersList]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate(
            [
                'name' => 'required|min:3|max:150',
                'description' => 'required|min:3|max:2000',
                'weight' => 'required',
                'measurement_id' => 'exists:measurement,id',
                'supplier_id' => 'exists:supplier,id',
            ],
            [
                'required' => 'O campo deve ser preenchido!',
                'min' => 'O campo deve conter no mínimo 3 caracteres!',
                'max' => 'Limite de caracteres atingido!'
            ]
        );

        $product = new Product();
        $product->fill($request->all());

        if ($product->save()) {
            return redirect()->route('products.index');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);

        $measurementList = Measurement::all();

        $suppliersList = Supplier::all();

        return view('app.product.show', ['product' => $product, 'measurementList' => $measurementList, 'suppliersList' => $suppliersList]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $product = Product::find($id);

        $measurementList = Measurement::all();

        $suppliersList = Supplier::all();

        return view('app.product.edit', ['product' => $product, 'measurementList' => $measurementList, 'suppliersList' => $suppliersList]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate(
            [
                'name' => 'required|min:3|max:150',
                'description' => 'required|min:3|max:2000',
                'weight' => 'required',
                'measurement_id' => 'exists:measurement,id',
                'supplier_id' => 'exists:supplier,id',
            ],
            [
                'required' => 'O campo deve ser preenchido!',
                'min' => 'O campo deve conter no mínimo 3 caracteres!',
                'max' => 'Limite de caracteres atingido!'
            ]
        );

        $product = Product::find($id);

        if ($product->update($request->all())) {
            return redirect()->route('products.index');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $product = Product::find($id);

        if ($product->delete()) {

            return redirect()->route('products.index');

        }

    }
}

resources/views/app/product/create.blade.php
@extends('app.layouts.default')

@section('title', 'Produtos')

@section('content-body')
    <div class="page-title-small">
        <h1>Produtos - Adicionar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('products.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('products.store') }}" method="post">
                @csrf

                <input type="hidden" name="id" value="{{ $product->id ?? old('id') }}">

                <input type="text" name="name" value="{{ $product->name ?? old('name') }}" placeholder="Nome">
                @component('site.layouts.errors', ["inputName" => "name"]) @endcomponent

                <input type="text" name="description" value="{{ $product->description ?? old('description') }}" placeholder="Descrição">
                @component('site.layouts.errors', ["inputName" => "description"]) @endcomponent

                <input type="number" name="weight" value="{{ $product->weight ?? old('weight') }}" placeholder="Peso">
                @component('site.layouts.errors', ["inputName" => "weight"]) @endcomponent

                <select name="measurement_id">
                    @foreach ($measurementList as $measurement)
                        <option value="{{$measurement->id}}" {{ old('measurement_id') == $measurement->id ? 'selected' : '' }} >{{ $measurement->unit }} - {{ $measurement->alias }}</option>
                    @endforeach
                </select>
                @component('site.layouts.errors', ["inputName" => "measurement_id"]) @endcomponent

                <select name="supplier_id">
                    @foreach ($suppliersList as $supplier)
                        <option value="{{$supplier->id}}" {{ old('supplier_id') == $supplier->id ? 'selected' : '' }} >{{ $supplier->nome }}</option>
                    @endforeach
                </select>
                @component('site.layouts.errors', ["inputName" => "supplier_id"]) @endcomponent

                <button type="submit">Salvar</button>

            </form>

        </div>

    </div>
@endsection

resources/views/app/product/edit.blade.php
@extends('app.layouts.default')

@section('title', 'Produtos')

@section('content-body')
    <div class="page-title-small">
        <h1>Produtos - Editar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('products.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('products.update', [$product->id]) }}" method="post">
                @csrf
                @method('PUT')
                <input type="text" name="name" value="{{ $product->name ?? old('name') }}" placeholder="Nome">
                @component('site.layouts.errors', ["inputName" => "name"]) @endcomponent

                <input type="text" name="description" value="{{ $product->description ?? old('description') }}" placeholder="Descrição">
                @component('site.layouts.errors', ["inputName" => "description"]) @endcomponent

                <input type="number" name="weight" value="{{ $product->weight ?? old('weight') }}" placeholder="Peso">
                @component('site.layouts.errors', ["inputName" => "weight"]) @endcomponent

                <select name="measurement_id">
                    @foreach ($measurementList as $measurement)
                        <option value="{{$measurement->id}}" {{ (old('measurement_id') == $measurement->id || $product->measurement_id == $measurement->id)  ? 'selected' : '' }} >{{ $measurement->unit }} - {{ $measurement->alias }}</option>
                    @endforeach
                </select>
                @component('site.layouts.errors', ["inputName" => "measurement_id"]) @endcomponent

                <select name="supplier_id">
                    @foreach ($suppliersList as $supplier)
                        <option value="{{$supplier->id}}" {{ (old('supplier_id') == $supplier->id || $product->supplier_id == $supplier->id)  ? 'selected' : '' }} >{{ $supplier->nome }}</option>
                    @endforeach
                </select>
                @component('site.layouts.errors', ["inputName" => "supplier_id"]) @endcomponent

                <button type="submit">Salvar</button>

            </form>

        </div>

    </div>
@endsection

resources/views/app/product/index.blade.php
@extends('app.layouts.default')

@section('title', 'Produtos')

@section('content-body')
    <div class="page-title-small">
        <h1>Produtos</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('products.create') }}">Novo</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('products.index') }}" method="get">
                @csrf
                <input type="text" name="name" placeholder="Nome">
                <input type="text" name="weight" placeholder="Peso">
                <input type="text" name="description" placeholder="Descrição">
                <input type="text" name="measurement_id" placeholder="Unidade">

                <button type="submit">Pesquisar</button>

            </form>

        </div>

    </div>

    <div class="informacao-pagina">

        <div style="width: 90%; margin-left: auto; margin-right: auto; ">

            <table border="1" width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Fornecedor</th>
                        <th>Descrição</th>
                        <th>Peso</th>
                        <th>UM</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($productsList as $product)

                        <tr>
                            <td>
                                {{ $product->id }}
                            </td>
                            <td>
                                {{ $product->name }}
                            </td>
                            <td>
                                {{ $product->supplier->nome }}
                            </td>
                            <td>
                                {{ $product->description }}
                            </td>
                            <td>
                                {{ $product->weight }}
                            </td>
                            <td>
                                {{ $product->measurement->unit }} - {{ $product->measurement->alias }}
                            </td>
                            <td>
                                <a href="{{ route('products.show', $product->id) }}">Visualizar</a>
                                <a href="{{ route('products.edit', $product->id) }}">Editar</a>

                                <form action="{{ route('products.destroy', $product->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit">Excluir</button>
                                </form>

                            </td>
                        </tr>

                    @endforeach
                </tbody>

                <footer>
                    <tr>
                        <td colspan="5"></td>
                        <td>
                            Total - {{ $productsList->total() }}
                        </td>
                    </tr>
                </footer>
            </table>

            <div>

                {{ $productsList->appends($queryParams)->links() }}

            </div>

        </div>

    </div>
@endsection

resources/views/app/product/show.blade.php
@extends('app.layouts.default')

@section('title', 'Produtos')

@section('content-body')
    <div class="page-title-small">
        <h1>Produtos - Editar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('products.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

                <input disabled type="text" name="id" value="{{ $product->id ?? old('id') }}">

                <input disabled type="text" name="name" value="{{ $product->name ?? old('name') }}" placeholder="Nome">
                @component('site.layouts.errors', ["inputName" => "name"]) @endcomponent

                <input disabled type="text" name="description" value="{{ $product->description ?? old('description') }}" placeholder="Descrição">
                @component('site.layouts.errors', ["inputName" => "description"]) @endcomponent

                <input disabled type="number" name="weight" value="{{ $product->weight ?? old('weight') }}" placeholder="Peso">
                @component('site.layouts.errors', ["inputName" => "weight"]) @endcomponent

                <select name="measurement_id" disabled>
                    @foreach ($measurementList as $measurement)
                        <option value="{{$measurement->id}}" {{ (old('measurement_id') == $measurement->id || $product->measurement_id == $measurement->id) ? 'selected' : '' }} >{{ $measurement->unit }} - {{ $measurement->alias }}</option>
                    @endforeach
                </select>
                @component('site.layouts.errors', ["inputName" => "measurement_id"]) @endcomponent
        </div>

    </div>
@endsection