routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'MainController@index')->name('site.index');

Route::get('/about', 'AboutController@index')->name('site.about');

Route::get('/contact', 'ContactController@index')->name('site.contact');

Route::post('/contact/send', 'ContactController@sendMessage')->name('site.contact.send');

Route::get('/login', 'LoginController@index')->name('site.login');

Route::post('/login', 'LoginController@authentication')->name('site.auth');

Route::middleware('auth.basic')->prefix('/app')->group(function() {

    Route::get('/home', 'HomeController@index')->name('app.home');

    Route::get('/logout', 'LoginController@logout')->name('app.logout');

    // Route::get('/clients', 'ClientController@index')->name('app.clients');

    Route::get('/suppliers', 'SupplierController@index')->name('app.suppliers');
    Route::get('/suppliers/add', 'SupplierController@add')->name('app.suppliers.add');
    Route::post('/suppliers/save', 'SupplierController@save')->name('app.suppliers.save');
    Route::get('/suppliers/edit/{id}', 'SupplierController@edit')->name('app.suppliers.edit');
    Route::get('/suppliers/delete/{id}', 'SupplierController@delete')->name('app.suppliers.delete');

    Route::resource('products', 'ProductController');

    Route::resource('clients', 'ClientController');

    Route::resource('solicitations', 'SolicitationController');

    Route::resource('clients-solicitations', 'ClientSolicitationController');

});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table = 'clients';

    protected $fillable = ['name', 'email', 'cpfCnpj', 'zipCode'];

    public function solicitations()
    {
        return $this->belongsTo('App\Solicitation');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (!empty($request->all())) {

            $clientsList = Client::with(['solicitations'])
                ->where('name', 'like', "%" . $request->input('name')."%")
                ->where('email', 'like', "%" . $request->input('email') . "%")
                ->where('cpfCnpj', 'like', "%" . $request->input('cpfCnpj') . "%")
                ->where('zipCode', 'like', "%" . $request->input('zipCode') . "%")
                ->paginate(20);

        } else {
            $clientsList = Client::with(['solicitations'])->paginate(20);
        }

        return view('app.client.index', ['clientsList' => $clientsList, 'queryParams' => $request->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('app.client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate(
            [
                'name' => 'required|min:3|max:150',
                'email' => 'required|email',
                'cpfCnpj' => 'required',
                'zipCode' => 'required',
            ],
            [
                'required' => 'O campo deve ser preenchido!',
                'min' => 'O campo deve conter no mínimo 3 caracteres!',
                'max' => 'Limite de caracteres atingido!'
            ]
        );

        $client = new Client();
        $client->fill($request->all());

        if ($client->save()) {
            return redirect()->route('clients.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $client = Client::find($id);

        return view('app.client.show', ['client' => $client]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $client = Client::find($id);

        return view('app.client.edit', ['client' => $client]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate(
            [
                'name' => 'required|min:3|max:150',
                'email' => 'required|email',
                'cpfCnpj' => 'required',
                'zipCode' => 'required',
            ],
            [
                'required' => 'O campo deve ser preenchido!',
                'min' => 'O campo deve conter no mínimo 3 caracteres!',
                'max' => 'Limite de caracteres atingido!'
            ]
        );

        $client = Client::find($id);

        if ($client->update($request->all())) {
            return redirect()->route('clients.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $client = Client::find($id);

        if ($client->delete()) {

            return redirect()->route('clients.index');

        }
    }
}

resources/views/app/client/create.blade.php
@extends('app.layouts.default')

@section('title', 'Clientes')

@section('content-body')
    <div class="page-title-small">
        <h1>Clientes - Adicionar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('clients.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('clients.store') }}" method="post">
                @csrf

                <input type="hidden" name="id" value="{{ $client->id ?? old('id') }}">

                <input type="text" name="name" value="{{ $client->name ?? old('name') }}" placeholder="Nome">
                @component('site.layouts.errors', ["inputName" => "name"]) @endcomponent

                <input type="text" name="email" value="{{ $client->email ?? old('email') }}" placeholder="E-mail">
                @component('site.layouts.errors', ["inputName" => "email"]) @endcomponent

                <input type="number" name="cpfCnpj" value="{{ $client->cpfCnpj ?? old('cpfCnpj') }}" placeholder="CPF/CNPJ">
                @component('site.layouts.errors', ["inputName" => "cpfCnpj"]) @endcomponent

                <input type="number" name="zipCode" value="{{ $client->zipCode ?? old('zipCode') }}" placeholder="CEP">
                @component('site.layouts.errors', ["inputName" => "zipCode"]) @endcomponent

                <button type="submit">Salvar</button>

            </form>

        </div>

    </div>
@endsection

resources/views/app/client/edit.blade.php
@extends('app.layouts.default')

@section('title', 'Clientes')

@section('content-body')
    <div class="page-title-small">
        <h1>Clientes - Editar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('clients.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('clients.update', [$client->id]) }}" method="post">
                @csrf
                @method('PUT')
                <input type="text" name="name" value="{{ $client->name ?? old('name') }}" placeholder="Nome">
                @component('site.layouts.errors', ["inputName" => "name"]) @endcomponent

                <input type="text" name="email" value="{{ $client->email ?? old('email') }}" placeholder="E-mail">
                @component('site.layouts.errors', ["inputName" => "email"]) @endcomponent

                <input type="number" name="cpfCnpj" value="{{ $client->cpfCnpj ?? old('cpfCnpj') }}" placeholder="CPF/CNPJ">
                @component('site.layouts.errors', ["inputName" => "cpfCnpj"]) @endcomponent

                <input type="number" name="zipCode" value="{{ $client->zipCode ?? old('zipCode') }}" placeholder="CEP">
                @component('site.layouts.errors', ["inputName" => "zipCode"]) @endcomponent

                <button type="submit">Salvar</button>

            </form>

        </div>

    </div>
@endsection

resources/views/app/client/index.blade.php
@extends('app.layouts.default')

@section('title', 'Clientes')

@section('content-body')
    <div class="page-title-small">
        <h1>Clientes</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('clients.create') }}">Novo</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('clients.index') }}" method="get">
                @csrf
                <input type="text" name="name" placeholder="Nome">
                <input type="text" name="email" placeholder="E-mail">
                <input type="text" name="cpfCnpj" placeholder="CPF/CNPJ">
                <input type="text" name="zipCode" placeholder="CEP">

                <button type="submit">Pesquisar</button>

            </form>

        </div>

    </div>

    <div class="informacao-pagina">

        <div style="width: 90%; margin-left: auto; margin-right: auto; ">

            <table border="1" width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th>CPF/CNPJ</th>
                        <th>CEP</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($clientsList as $client)

                        <tr>
                            <td>
                                {{ $client->id }}
                            </td>
                            <td>
                                {{ $client->name }}
                            </td>
                            <td>
                                {{ $client->email}}
                            </td>
                            <td>
                                {{ $client->cpfCnpj }}
                            </td>
                            <td>
                                {{ $client->zipCode }}
                            </td>
                            <td>
                                <a href="{{ route('clients.show', $client->id) }}">Visualizar</a>
                                <a href="{{ route('clients.edit', $client->id) }}">Editar</a>

                                <form action="{{ route('clients.destroy', $client->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit">Excluir</button>
                                </form>

                            </td>
                        </tr>

                    @endforeach
                </tbody>

                <footer>
                    <tr>
                        <td colspan="5"></td>
                        <td>
                            Total - {{ $clientsList->total() }}
                        </td>
                    </tr>
                </footer>
            </table>

            <div>

                {{ $clientsList->appends($queryParams)->links() }}

            </div>

        </div>

    </div>
@endsection

resources/views/app/client/show.blade.php
@extends('app.layouts.default')

@section('title', 'Clientes')

@section('content-body')
    <div class="page-title-small">
        <h1>Clientes - Editar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('clients.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

                <input disabled type="text" name="id" value="{{ $client->id ?? old('id') }}">

                <input disabled type="text" name="name" value="{{ $client->name ?? old('name') }}" placeholder="Nome">
                @component('site.layouts.errors', ["inputName" => "name"]) @endcomponent

                <input disabled type="text" name="email" value="{{ $client->email ?? old('email') }}" placeholder="E-mail">
                @component('site.layouts.errors', ["inputName" => "email"]) @endcomponent

                <input disabled type="number" name="cpfCnpj" value="{{ $client->cpfCnpj ?? old('cpfCnpj') }}" placeholder="CPF/CNPJ">
                @component('site.layouts.errors', ["inputName" => "cpfCnpj"]) @endcomponent

                <input disabled type="number" name="zipCode" value="{{ $client->zipCode ?? old('zipCode') }}" placeholder="CEP">
                @component('site.layouts.errors', ["inputName" => "zipCode"]) @endcomponent

        </div>

    </div>
@endsection