routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'MainController@index')->name('site.index');

Route::get('/about', 'AboutController@index')->name('site.about');

Route::get('/contact', 'ContactController@index')->name('site.contact');

Route::post('/contact/send', 'ContactController@sendMessage')->name('site.contact.send');

Route::get('/login', 'LoginController@index')->name('site.login');

Route::post('/login', 'LoginController@authentication')->name('site.auth');

Route::middleware('auth.basic')->prefix('/app')->group(function() {

    Route::get('/home', 'HomeController@index')->name('app.home');

    Route::get('/logout', 'LoginController@logout')->name('app.logout');

    // Route::get('/clients', 'ClientController@index')->name('app.clients');

    Route::get('/suppliers', 'SupplierController@index')->name('app.suppliers');
    Route::get('/suppliers/add', 'SupplierController@add')->name('app.suppliers.add');
    Route::post('/suppliers/save', 'SupplierController@save')->name('app.suppliers.save');
    Route::get('/suppliers/edit/{id}', 'SupplierController@edit')->name('app.suppliers.edit');
    Route::get('/suppliers/delete/{id}', 'SupplierController@delete')->name('app.suppliers.delete');

    Route::resource('products', 'ProductController');

    Route::resource('clients', 'ClientController');

    Route::resource('solicitations', 'SolicitationController');

    Route::resource('clients-solicitations', 'ClientSolicitationController');

});

resources/views/app/clientsSolicitations/create.blade.php
@extends('app.layouts.default')

@section('title', 'Adicionar produto ao pedido')

@section('content-body')
    <div class="page-title-small">
        <h1>Adicionar produto ao pedido</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('solicitations.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">
            <h3>Pedido do cliente: {{ $solicitation->clients->name }}</h3>

            <hr>

            <h4>Itens do pedido</h4>

            <table border="1" width="100%">
                <thead>
                    <tr>
                        <td><b>Produtos</b></td>
                        <td><b>Quantidade</b></td>
                        <td><b>Ações</b></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($solicitation->products as $products)
                        <tr>
                            <td>
                                {{ $products->name }}
                            </td>

                            <td>
                                {{ $products->quantity }}
                            </td>

                            <td>
                                <form id="form_{{$products->pivot->id}}" action="{{ route('clients-solicitations.destroy', $products->pivot->id) }}" method="post">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit">
                                        Remover
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <form action="{{ route('clients-solicitations.store') }}" method="post">
                @csrf

                <input type="hidden"  name="solicitation_id" value="{{ $solicitation->id }}" >

                <select name="product_id">
                    <option value=""> -- Selecione um produto -- </option>
                    @foreach ($productList as $product)
                        <option value="{{$product->id}}" {{ (old('product_id') == $product->id) ? 'selected' : '' }} >{{ $product->name }}</option>
                    @endforeach
                </select>
                @component('site.layouts.errors', ["inputName" => "product_id"]) @endcomponent

                <input type="number" name="quantity" value="{{ old('quantity') ?? '' }}">
                @component('site.layouts.errors', ["inputName" => "quantity"]) @endcomponent

                <button type="submit">Salvar</button>

            </form>

        </div>

    </div>
@endsection

resources/views/app/clientsSolicitations/edit.blade.php
@extends('app.layouts.default')

@section('title', 'Pedidos')

@section('content-body')
    <div class="page-title-small">
        <h1>Pedidos - Editar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('solicitations.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('solicitations.update', [$solicitation->id]) }}" method="post">
                @csrf
                @method('PUT')

                <select name="client_id">
                    @foreach ($clientList as $client)
                        <option value="{{$client->id}}" {{ (old('client_id') == $client->id || $solicitation->client_id == $client->id) ? 'selected' : '' }} >{{ $client->name }}</option>
                    @endforeach
                </select>
                @component('site.layouts.errors', ["inputName" => "client_id"]) @endcomponent

                <button type="submit">Salvar</button>

            </form>

        </div>

    </div>
@endsection

resources/views/app/clientsSolicitations/index.blade.php
@extends('app.layouts.default')

@section('title', 'Pedidos')

@section('content-body')
    <div class="page-title-small">
        <h1>Pedidos</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('solicitations.create') }}">Novo</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

            <form action="{{ route('solicitations.index') }}" method="get">
                @csrf
                <input type="text" name="name" placeholder="Nome">
                <input type="text" name="email" placeholder="E-mail">
                <input type="text" name="cpfCnpj" placeholder="CPF/CNPJ">
                <input type="text" name="zipCode" placeholder="CEP">

                <button type="submit">Pesquisar</button>

            </form>

        </div>

    </div>

    <div class="informacao-pagina">

        <div style="width: 90%; margin-left: auto; margin-right: auto; ">

            <table border="1" width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Cliente</th>
                        <th>Produtos</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($solicitationsList as $solicitation)

                        <tr>
                            <td>
                                {{ $solicitation->id }}
                            </td>
                            <td>
                                {{ $solicitation->clients->name }}
                            </td>
                            <td>
                                <a href="{{ route('clients-solicitations.create') }}">Adicionar Produto</a>
                            </td>
                            <td>
                                <a href="{{ route('solicitations.show', $solicitation->id) }}">Visualizar</a>
                                <a href="{{ route('solicitations.edit', $solicitation->id) }}">Editar</a>

                                <form action="{{ route('solicitations.destroy', $solicitation->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit">Excluir</button>
                                </form>

                            </td>
                        </tr>

                    @endforeach
                </tbody>

                <footer>
                    <tr>
                        <td colspan="2"></td>
                        <td>
                            Total - {{ $solicitationsList->total() }}
                        </td>
                    </tr>
                </footer>
            </table>

            <div>

                {{ $solicitationsList->appends($queryParams)->links() }}

            </div>

        </div>

    </div>
@endsection

resources/views/app/clientsSolicitations/show.blade.php
@extends('app.layouts.default')

@section('title', 'Pedidos')

@section('content-body')
    <div class="page-title-small">
        <h1>Pedidos - Editar</h1>
    </div>

    <div class="menu">
        <ul>
            <li><a href="{{ route('solicitations.index') }}">Voltar</a></li>
        </ul>
    </div>

    <div class="informacao-pagina">

        <div style="width: 60%; margin-left: auto; margin-right: auto; ">

                <input disabled type="text" name="id" value="{{ $solicitation->id ?? old('id') }}">

                <select name="client_id" disabled>
                    @foreach ($clientList as $client)
                        <option value="{{$client->id}}" {{ ($solicitation->client_id == $client->id) ? 'selected' : '' }} >{{ $client->name }}</option>
                    @endforeach
                </select>

        </div>

    </div>
@endsection